# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "SQLite.swift" = "sha256-BkWOEy1f7nyMQdM3GVe6hVMptLkTMA/gRNbjQP0sx2o=";
    "swift-toolchain-sqlite" = "sha256-6ZVutGmfK+Jc7y9qTgvnHEpsCtHejPxWF0o0oj2eAFk=";
  };
}
